; NERD Compiled Program
; Generated by NERD Bootstrap Compiler
declare double @print_buffer()
declare double @wasm_get_shared_buffer()


declare double @llvm.fabs.f64(double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)

declare i32 @printf(i8*, ...)

declare i8* @nerd_http_get(i8*)
declare i8* @nerd_http_post(i8*, i8*)
declare void @nerd_http_free(i8*)
declare i8* @nerd_http_get_json(i8*)
declare i8* @nerd_http_post_json(i8*, i8*)
declare i8* @nerd_http_post_json_body(i8*, i8*)
declare i8* @nerd_http_request(i8*, i8*, i8*, i8*)
declare i8* @nerd_http_get_full(i8*, i8*)
declare i8* @nerd_http_post_full(i8*, i8*, i8*)
declare i8* @nerd_http_put(i8*, i8*, i8*)
declare i8* @nerd_http_delete(i8*, i8*)
declare i8* @nerd_http_patch(i8*, i8*, i8*)
declare i8* @nerd_http_auth_bearer(i8*)
declare i8* @nerd_http_auth_basic(i8*, i8*)

declare i8* @nerd_mcp_list(i8*)
declare i8* @nerd_mcp_send(i8*, i8*, i8*)
declare i8* @nerd_mcp_use(i8*, i8*, i8*)
declare i8* @nerd_mcp_init(i8*)
declare i8* @nerd_mcp_resources(i8*)
declare i8* @nerd_mcp_read(i8*, i8*)
declare i8* @nerd_mcp_prompts(i8*)
declare i8* @nerd_mcp_prompt(i8*, i8*, i8*)
declare i8* @nerd_mcp_log(i8*, i8*)
declare void @nerd_mcp_free(i8*)

declare i8* @nerd_llm_claude(i8*)
declare void @nerd_llm_free(i8*)

declare i8* @nerd_json_new()
declare i8* @nerd_json_parse(i8*)
declare i8* @nerd_json_get_string(i8*, i8*)
declare double @nerd_json_get_number(i8*, i8*)
declare i32 @nerd_json_get_bool(i8*, i8*)
declare i8* @nerd_json_get_object(i8*, i8*)
declare i32 @nerd_json_count(i8*, i8*)
declare i32 @nerd_json_has(i8*, i8*)
declare void @nerd_json_set_string(i8*, i8*, i8*)
declare void @nerd_json_set_number(i8*, i8*, double)
declare void @nerd_json_set_bool(i8*, i8*, i32)
declare i8* @nerd_json_stringify(i8*)
declare void @nerd_json_free(i8*)
declare void @nerd_json_free_string(i8*)

@.fmt_num = private constant [4 x i8] c"%g\0A\00"
@.fmt_str = private constant [4 x i8] c"%s\0A\00"
@.fmt_int = private constant [6 x i8] c"%.0f\0A\00"

@.str0 = private constant [52 x i8] c"<!DOCTYPE html><html><head><title>Dashboard</title>\00"
@.str1 = private constant [71 x i8] c"<meta name=\22viewport\22 content=\22width=device-width, initial-scale=1.0\22>\00"
@.str2 = private constant [8 x i8] c"<style>\00"
@.str3 = private constant [160 x i8] c"body{margin:0;height:100vh;display:flex;align-items:center;justify-content:center;background:#030507;color:#fff;font-family:-apple-system,system-ui,sans-serif}\00"
@.str4 = private constant [64 x i8] c"#app{text-align:center;width:100%;max-width:400px;padding:20px}\00"
@.str5 = private constant [70 x i8] c"h1{font-weight:300;letter-spacing:2px;margin-bottom:40px;opacity:0.8}\00"
@.str6 = private constant [55 x i8] c".input-container{position:relative;margin-bottom:20px}\00"
@.str7 = private constant [176 x i8] c"input{width:100%;padding:15px 0;background:none;border:none;border-bottom:2px solid #333;color:#fff;font-size:32px;text-align:center;outline:none;transition:border-color 0.3s}\00"
@.str8 = private constant [34 x i8] c"input:focus{border-color:#78B6AD}\00"
@.str9 = private constant [66 x i8] c"input::placeholder{color:#333;text-transform:none;font-size:18px}\00"
@.str10 = private constant [177 x i8] c"button{margin-top:20px;background:#78B6AD;border:none;color:#030507;padding:12px 30px;border-radius:25px;font-weight:bold;cursor:pointer;transition:transform 0.2s,opacity 0.2s}\00"
@.str11 = private constant [48 x i8] c"button:hover{transform:scale(1.05);opacity:0.9}\00"
@.str12 = private constant [64 x i8] c"button:disabled{background:#333;opacity:0.5;cursor:not-allowed}\00"
@.str13 = private constant [49 x i8] c".hint{font-size:12px;color:#555;margin-top:10px}\00"
@.str14 = private constant [16 x i8] c"</style></head>\00"
@.str15 = private constant [21 x i8] c"<body><div id=\22app\22>\00"
@.str16 = private constant [19 x i8] c"<h1>WATCHLIST</h1>\00"
@.str17 = private constant [30 x i8] c"<div class=\22input-container\22>\00"
@.str18 = private constant [112 x i8] c"<input type=\22text\22 id=\22symbol\22 placeholder=\22ENTER SYMBOL\22 maxlength=\2210\22 spellcheck=\22false\22 autocomplete=\22off\22>\00"
@.str19 = private constant [7 x i8] c"</div>\00"
@.str20 = private constant [53 x i8] c"<button id=\22btn\22 onclick=\22sv()\22>ADD TO LIST</button>\00"
@.str21 = private constant [60 x i8] c"<div class=\22hint\22>MOE AI RESEARCH \E2\80\A2 STOCKS & CRYPTO</div>\00"
@.str22 = private constant [7 x i8] c"</div>\00"
@.str23 = private constant [9 x i8] c"<script>\00"
@.str24 = private constant [49 x i8] c"const input = document.getElementById('symbol');\00"
@.str25 = private constant [44 x i8] c"const btn = document.getElementById('btn');\00"
@.str26 = private constant [118 x i8] c"input.addEventListener('input', (e) => { e.target.value = e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''); });\00"
@.str27 = private constant [73 x i8] c"window.APP={token:localStorage.getItem('nerd_token')||'nerd-token-123'};\00"
@.str28 = private constant [21 x i8] c"async function sv(){\00"
@.str29 = private constant [32 x i8] c"const val = input.value.trim();\00"
@.str30 = private constant [40 x i8] c"if(!val){alert('Empty Symbol');return;}\00"
@.str31 = private constant [51 x i8] c"btn.innerText='RESEARCHING...'; btn.disabled=true;\00"
@.str32 = private constant [5 x i8] c"try{\00"
@.str33 = private constant [70 x i8] c"const res=await fetch('/api/admin/generate?token='+window.APP.token,{\00"
@.str34 = private constant [15 x i8] c"method:'POST',\00"
@.str35 = private constant [35 x i8] c"body:JSON.stringify({symbol:val}),\00"
@.str36 = private constant [44 x i8] c"headers:{'Content-Type':'application/json'}\00"
@.str37 = private constant [4 x i8] c"});\00"
@.str38 = private constant [29 x i8] c"const data=await res.json();\00"
@.str39 = private constant [127 x i8] c"if(data.success){alert('Moe has finished analyzing '+val+'. Post created!');input.value='';}else{alert('Error: '+data.error);}\00"
@.str40 = private constant [38 x i8] c"}catch(e){alert('Connection Error');}\00"
@.str41 = private constant [57 x i8] c"finally{btn.innerText='ADD TO LIST';btn.disabled=false;}\00"
@.str42 = private constant [2 x i8] c"}\00"
@.str43 = private constant [93 x i8] c"input.addEventListener('keypress', (e) => { if(e.key === 'Enter' && !btn.disabled) sv(); });\00"
@.str44 = private constant [3 x i8] c"</\00"
@.str45 = private constant [22 x i8] c"script></body></html>\00"
@.str46 = private constant [8 x i8] c"<style>\00"
@.str47 = private constant [428 x i8] c":root{--sans-font:-apple-system,BlinkMacSystemFont,'Avenir Next',Avenir,'Nimbus Sans L',Roboto,'Noto Sans','Segoe UI',Arial,Helvetica,'Helvetica Neue',sans-serif;--mono-font:Consolas,Menlo,Monaco,'Andale Mono','Ubuntu Mono',monospace;--standard-border-radius:5px;--bg:#EEEEEE;--bg-light:#CBCDCD;--text:#41474E;--text-light:#646868;--accent:#D26878;--accent-light:#e08f67;--accent-text:var(--bg);--border:#646868;--link:#5690AF}\00"
@.str48 = private constant [224 x i8] c"@media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#222529;--bg-light:#464949;--text:#D6D6D6;--text-light:#DBD5BC;--accent:#78B6AD;--accent-light:#87C9E5;--accent-text:var(--bg);--border:#DBD5BC;--link:#E2AEA2}}\00"
@.str49 = private constant [201 x i8] c"[data-theme=dark]{color-scheme:dark;--bg:#222529;--bg-light:#464949;--text:#D6D6D6;--text-light:#DBD5BC;--accent:#78B6AD;--accent-light:#87C9E5;--accent-text:var(--bg);--border:#DBD5BC;--link:#E2AEA2}\00"
@.str50 = private constant [203 x i8] c"[data-theme=light]{color-scheme:light;--bg:#EEEEEE;--bg-light:#CBCDCD;--text:#41474E;--text-light:#646868;--accent:#D26878;--accent-light:#e08f67;--accent-text:var(--bg);--border:#646868;--link:#5690AF}\00"
@.str51 = private constant [44 x i8] c"*{box-sizing:border-box;margin:0;padding:0}\00"
@.str52 = private constant [82 x i8] c"html{color-scheme:light dark;font-family:var(--mono-font);scroll-behavior:smooth}\00"
@.str53 = private constant [212 x i8] c"body{min-height:100svh;font-size:1rem;display:grid;grid-template-columns:1fr min(47rem,90%) 1fr;grid-template-rows:auto 1fr auto;grid-row-gap:.625rem;color:var(--text);background-color:var(--bg);line-height:1.6}\00"
@.str54 = private constant [22 x i8] c"body>*{grid-column:2}\00"
@.str55 = private constant [144 x i8] c"#nav-bar{padding:0.625rem 0 0;display:flex;flex-wrap:wrap;gap:0.25rem;justify-content:flex-end;align-items:center;font-family:var(--mono-font)}\00"
@.str56 = private constant [68 x i8] c"#nav-bar a{color:var(--text);text-decoration:none;padding:0 .25rem}\00"
@.str57 = private constant [63 x i8] c"#nav-bar a:hover{background-color:var(--link);color:var(--bg)}\00"
@.str58 = private constant [65 x i8] c"h1,h2,h3,h4,h5,h6{margin:.5em 0;line-height:1.1;font-weight:700}\00"
@.str59 = private constant [60 x i8] c"h1{font-size:2rem}h2{font-size:1.75rem}h3{font-size:1.5rem}\00"
@.str60 = private constant [100 x i8] c"h1::before,h2::before,h3::before,h4::before,h5::before,h6::before{color:var(--accent);content:'# '}\00"
@.str61 = private constant [34 x i8] c"p{margin:1rem 0;text-wrap:pretty}\00"
@.str62 = private constant [94 x i8] c"a,a:visited{text-decoration:none;border-radius:.125rem;color:var(--link);transition:all 0.2s}\00"
@.str63 = private constant [54 x i8] c"a:hover{background-color:var(--link);color:var(--bg)}\00"
@.str64 = private constant [56 x i8] c"ul{list-style:square;margin:1rem 0;padding-left:1.5rem}\00"
@.str65 = private constant [47 x i8] c"ul li{margin-bottom:.125rem;position:relative}\00"
@.str66 = private constant [49 x i8] c"ul li::marker{content:'\C2\BB ';color:var(--accent)}\00"
@.str67 = private constant [68 x i8] c"ul li:hover::marker{content:'# ';font-weight:700;color:var(--link)}\00"
@.str68 = private constant [153 x i8] c"blockquote{margin:1rem 0 1rem 1.25rem;padding:.5rem 0 0 .5rem;border-inline-start:.375rem solid var(--accent);font-style:italic;color:var(--text-light)}\00"
@.str69 = private constant [70 x i8] c"footer{color:var(--text-light);font-size:.875rem;padding:1rem 0 2rem}\00"
@.str70 = private constant [58 x i8] c"footer hr{border:1px dashed var(--accent);margin:.5rem 0}\00"
@.str71 = private constant [96 x i8] c"#footer-container{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center}\00"
@.str72 = private constant [184 x i8] c".theme-toggle{cursor:pointer;background:none;border:none;font-size:1.25rem;color:var(--text);opacity:0.7;padding:0 .5rem;display:inline-flex;align-items:center;justify-content:center}\00"
@.str73 = private constant [51 x i8] c".theme-toggle:hover{opacity:1;color:var(--accent)}\00"
@.str74 = private constant [116 x i8] c"code{font-family:var(--mono-font);padding:0 .125rem;border-radius:3px;color:var(--bg);background-color:var(--text)}\00"
@.str75 = private constant [157 x i8] c"pre{border:1px solid var(--accent);border-radius:var(--standard-border-radius);background-color:var(--bg-light);padding:.625rem;overflow:auto;margin:1rem 0}\00"
@.str76 = private constant [50 x i8] c"pre code{background:none;color:inherit;padding:0}\00"
@.str77 = private constant [30 x i8] c"article{margin-bottom:2.5rem}\00"
@.str78 = private constant [71 x i8] c".post-meta{font-size:.9rem;color:var(--text-light);margin-bottom:1rem}\00"
@.str79 = private constant [9 x i8] c"</style>\00"
@.str80 = private constant [60 x i8] c"<!DOCTYPE html><html lang=\22en\22><head><meta charset=\22UTF-8\22>\00"
@.str81 = private constant [71 x i8] c"<meta name=\22viewport\22 content=\22width=device-width, initial-scale=1.0\22>\00"
@.str82 = private constant [8 x i8] c"<title>\00"
@.str83 = private constant [9 x i8] c"</title>\00"
@.str84 = private constant [83 x i8] c"<link rel=\22alternate\22 type=\22application/rss+xml\22 title=\22RSS Feed\22 href=\22/rss.xml\22>\00"
@.str85 = private constant [32 x i8] c"</head><body><nav id=\22nav-bar\22>\00"
@.str86 = private constant [113 x i8] c"<a href=\22/\22> /home/ </a><a href=\22/about\22> /about/ </a><a href=\22/blog\22> /blog/ </a><a href=\22/admin\22> /admin/ </a>\00"
@.str87 = private constant [72 x i8] c"<div class=\22theme-toggle\22 onclick=\22toggleTheme()\22>\E2\98\80</div></nav><main>\00"
@.str88 = private constant [47 x i8] c"</main><footer><hr><div id=\22footer-container\22>\00"
@.str89 = private constant [99 x i8] c"<p>Made using <a href=\22https://nerd-lang.org\22>nerd</a> | <a href=\22/admin\22>Admin</a></div></footer>\00"
@.str90 = private constant [9 x i8] c"<script>\00"
@.str91 = private constant [117 x i8] c"(function(){var t=localStorage.getItem('theme')||'light';document.documentElement.setAttribute('data-theme',t);})();\00"
@.str92 = private constant [187 x i8] c"function toggleTheme(){var h=document.documentElement,c=h.getAttribute('data-theme')||'light',n=c==='dark'?'light':'dark';h.setAttribute('data-theme',n);localStorage.setItem('theme',n);}\00"
@.str93 = private constant [24 x i8] c"</script></body></html>\00"
@.str94 = private constant [8 x i8] c"anemone\00"
@.str95 = private constant [32 x i8] c"<h2 id=\22overview\22>Overview</h2>\00"
@.str96 = private constant [267 x i8] c"<p>Research Moe Capital is an AI-native investment platform delivering high-signal analysis for stocks and crypto assets. We replace market noise with deep investigations into unit economics, competitive moats, and the timeless principles of business psychology.</p>\00"
@.str97 = private constant [298 x i8] c"<p>Every analysis is performed by <strong>Moe</strong>, our automated researcher modeled after the analytical precision of Morgan Housel. Moe follows a rigorous 13-point framework\E2\80\94from revenue quality to capital allocation\E2\80\94distilling complex businesses into precise, actionable narratives.</p>\00"
@.str98 = private constant [114 x i8] c"<blockquote><p><em>\E2\80\9CSimplicity is the ultimate sophistication\E2\80\94especially in finance.\E2\80\9D</em></p></blockquote>\00"
@.str99 = private constant [36 x i8] c"<h2 id=\22blog-posts\22>Blog Posts</h2>\00"
@.str100 = private constant [74 x i8] c"<p>Explore our insightful financial research on a variety of symbols:</p>\00"
@.str101 = private constant [5 x i8] c"<ul>\00"
@.str102 = private constant [6 x i8] c"</ul>\00"
@.str103 = private constant [24 x i8] c"<h2 id=\22tags\22>Tags</h2>\00"
@.str104 = private constant [36 x i8] c"<p>Browse our analysis by tags:</p>\00"
@.str105 = private constant [108 x i8] c"<ul><li>\F0\9F\A5\A3 <a href=\22#\22>Insight</a><li>\F0\9F\94\A5 <a href=\22#\22>Analysis</a><li>\F0\9F\88\9A <a href=\22#\22>Timeless</a></ul>\00"
@.str106 = private constant [46 x i8] c"<h2 id=\22online-presence\22>Online Presence</h2>\00"
@.str107 = private constant [31 x i8] c"<p>Stay connected with us:</p>\00"
@.str108 = private constant [207 x i8] c"<ul><li>Email: <a href=\22mailto:moe@example.com\22>moe@example.com</a><li>Code Repositories: <a href=\22https://github.com/criticalinsight/nerd-cms\22>criticalinsight@GitHub</a><li>@MoeResearch anywhere else.</ul>\00"
@.str109 = private constant [16 x i8] c"anemone | About\00"
@.str110 = private constant [23 x i8] c"<article class=\22post\22>\00"
@.str111 = private constant [52 x i8] c"<header class=\22post-header\22><h1>About</h1></header>\00"
@.str112 = private constant [27 x i8] c"<div class=\22post-content\22>\00"
@.str113 = private constant [247 x i8] c"<p>This is NERD CMS, a high-performance Content Management System built with the NERD programming language and deployed on Cloudflare Workers. It combines the efficiency of WebAssembly with the intelligence of modern AI assistants like 'Moe'.</p>\00"
@.str114 = private constant [179 x i8] c"<div style=\22margin: 2rem 0; padding: 1rem; border: 1px dashed var(--accent); border-radius: 5px; text-align: center;\22><i>\22Simplicity is a prerequisite for reliability.\22</i></div>\00"
@.str115 = private constant [65 x i8] c"<p>Nothing more, nothing less. <code>forget about it</code>.</p>\00"
@.str116 = private constant [7 x i8] c"</div>\00"
@.str117 = private constant [11 x i8] c"</article>\00"
@.str118 = private constant [15 x i8] c"anemone | Blog\00"
@.str119 = private constant [24 x i8] c"<h2>Blog Posts</h2><ul>\00"
@.str120 = private constant [6 x i8] c"</ul>\00"
@.str121 = private constant [15 x i8] c"anemone | Post\00"
@.str122 = private constant [10 x i8] c"<article>\00"
@.str123 = private constant [11 x i8] c"</article>\00"
@.str124 = private constant [68 x i8] c"<?xml version=\221.0\22 encoding=\22UTF-8\22 ?><rss version=\222.0\22><channel>\00"
@.str125 = private constant [68 x i8] c"<title>Research</title><link>https://research.moecapital.com</link>\00"
@.str126 = private constant [17 x i8] c"</channel></rss>\00"

define double @render_admin() {
entry:
  %t0 = getelementptr [52 x i8], [52 x i8]* @.str0, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [71 x i8], [71 x i8]* @.str1, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  %t2 = getelementptr [8 x i8], [8 x i8]* @.str2, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t2)
  %t3 = getelementptr [160 x i8], [160 x i8]* @.str3, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  %t4 = getelementptr [64 x i8], [64 x i8]* @.str4, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t4)
  %t5 = getelementptr [70 x i8], [70 x i8]* @.str5, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  %t6 = getelementptr [55 x i8], [55 x i8]* @.str6, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t6)
  %t7 = getelementptr [176 x i8], [176 x i8]* @.str7, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t7)
  %t8 = getelementptr [34 x i8], [34 x i8]* @.str8, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t8)
  %t9 = getelementptr [66 x i8], [66 x i8]* @.str9, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t9)
  %t10 = getelementptr [177 x i8], [177 x i8]* @.str10, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t10)
  %t11 = getelementptr [48 x i8], [48 x i8]* @.str11, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t11)
  %t12 = getelementptr [64 x i8], [64 x i8]* @.str12, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t12)
  %t13 = getelementptr [49 x i8], [49 x i8]* @.str13, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t13)
  %t14 = getelementptr [16 x i8], [16 x i8]* @.str14, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t14)
  %t15 = getelementptr [21 x i8], [21 x i8]* @.str15, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t15)
  %t16 = getelementptr [19 x i8], [19 x i8]* @.str16, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t16)
  %t17 = getelementptr [30 x i8], [30 x i8]* @.str17, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t17)
  %t18 = getelementptr [112 x i8], [112 x i8]* @.str18, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t18)
  %t19 = getelementptr [7 x i8], [7 x i8]* @.str19, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t19)
  %t20 = getelementptr [53 x i8], [53 x i8]* @.str20, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t20)
  %t21 = getelementptr [60 x i8], [60 x i8]* @.str21, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t21)
  %t22 = getelementptr [7 x i8], [7 x i8]* @.str22, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t22)
  %t23 = getelementptr [9 x i8], [9 x i8]* @.str23, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t23)
  %t24 = getelementptr [49 x i8], [49 x i8]* @.str24, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t24)
  %t25 = getelementptr [44 x i8], [44 x i8]* @.str25, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t25)
  %t26 = getelementptr [118 x i8], [118 x i8]* @.str26, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t26)
  %t27 = getelementptr [73 x i8], [73 x i8]* @.str27, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t27)
  %t28 = getelementptr [21 x i8], [21 x i8]* @.str28, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t28)
  %t29 = getelementptr [32 x i8], [32 x i8]* @.str29, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t29)
  %t30 = getelementptr [40 x i8], [40 x i8]* @.str30, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t30)
  %t31 = getelementptr [51 x i8], [51 x i8]* @.str31, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t31)
  %t32 = getelementptr [5 x i8], [5 x i8]* @.str32, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t32)
  %t33 = getelementptr [70 x i8], [70 x i8]* @.str33, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t33)
  %t34 = getelementptr [15 x i8], [15 x i8]* @.str34, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t34)
  %t35 = getelementptr [35 x i8], [35 x i8]* @.str35, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t35)
  %t36 = getelementptr [44 x i8], [44 x i8]* @.str36, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t36)
  %t37 = getelementptr [4 x i8], [4 x i8]* @.str37, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t37)
  %t38 = getelementptr [29 x i8], [29 x i8]* @.str38, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t38)
  %t39 = getelementptr [127 x i8], [127 x i8]* @.str39, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t39)
  %t40 = getelementptr [38 x i8], [38 x i8]* @.str40, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t40)
  %t41 = getelementptr [57 x i8], [57 x i8]* @.str41, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t41)
  %t42 = getelementptr [2 x i8], [2 x i8]* @.str42, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t42)
  %t43 = getelementptr [93 x i8], [93 x i8]* @.str43, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t43)
  %t44 = getelementptr [3 x i8], [3 x i8]* @.str44, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t44)
  %t45 = getelementptr [22 x i8], [22 x i8]* @.str45, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t45)
  ret double 0.0
}

define double @render_css() {
entry:
  %t0 = getelementptr [8 x i8], [8 x i8]* @.str46, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [428 x i8], [428 x i8]* @.str47, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  %t2 = getelementptr [224 x i8], [224 x i8]* @.str48, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t2)
  %t3 = getelementptr [201 x i8], [201 x i8]* @.str49, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  %t4 = getelementptr [203 x i8], [203 x i8]* @.str50, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t4)
  %t5 = getelementptr [44 x i8], [44 x i8]* @.str51, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  %t6 = getelementptr [82 x i8], [82 x i8]* @.str52, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t6)
  %t7 = getelementptr [212 x i8], [212 x i8]* @.str53, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t7)
  %t8 = getelementptr [22 x i8], [22 x i8]* @.str54, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t8)
  %t9 = getelementptr [144 x i8], [144 x i8]* @.str55, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t9)
  %t10 = getelementptr [68 x i8], [68 x i8]* @.str56, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t10)
  %t11 = getelementptr [63 x i8], [63 x i8]* @.str57, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t11)
  %t12 = getelementptr [65 x i8], [65 x i8]* @.str58, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t12)
  %t13 = getelementptr [60 x i8], [60 x i8]* @.str59, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t13)
  %t14 = getelementptr [100 x i8], [100 x i8]* @.str60, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t14)
  %t15 = getelementptr [34 x i8], [34 x i8]* @.str61, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t15)
  %t16 = getelementptr [94 x i8], [94 x i8]* @.str62, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t16)
  %t17 = getelementptr [54 x i8], [54 x i8]* @.str63, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t17)
  %t18 = getelementptr [56 x i8], [56 x i8]* @.str64, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t18)
  %t19 = getelementptr [47 x i8], [47 x i8]* @.str65, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t19)
  %t20 = getelementptr [49 x i8], [49 x i8]* @.str66, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t20)
  %t21 = getelementptr [68 x i8], [68 x i8]* @.str67, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t21)
  %t22 = getelementptr [153 x i8], [153 x i8]* @.str68, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t22)
  %t23 = getelementptr [70 x i8], [70 x i8]* @.str69, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t23)
  %t24 = getelementptr [58 x i8], [58 x i8]* @.str70, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t24)
  %t25 = getelementptr [96 x i8], [96 x i8]* @.str71, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t25)
  %t26 = getelementptr [184 x i8], [184 x i8]* @.str72, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t26)
  %t27 = getelementptr [51 x i8], [51 x i8]* @.str73, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t27)
  %t28 = getelementptr [116 x i8], [116 x i8]* @.str74, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t28)
  %t29 = getelementptr [157 x i8], [157 x i8]* @.str75, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t29)
  %t30 = getelementptr [50 x i8], [50 x i8]* @.str76, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t30)
  %t31 = getelementptr [30 x i8], [30 x i8]* @.str77, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t31)
  %t32 = getelementptr [71 x i8], [71 x i8]* @.str78, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t32)
  %t33 = getelementptr [9 x i8], [9 x i8]* @.str79, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t33)
  ret double 0.0
}

define double @render_head(double %arg0) {
entry:
  %t0 = getelementptr [60 x i8], [60 x i8]* @.str80, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [71 x i8], [71 x i8]* @.str81, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  %t2 = getelementptr [8 x i8], [8 x i8]* @.str82, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t2)
  %t3 = fadd double 0.0, %arg0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_num, i32 0, i32 0), double %t3)
  %t4 = getelementptr [9 x i8], [9 x i8]* @.str83, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t4)
  %t5 = getelementptr [83 x i8], [83 x i8]* @.str84, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  ; call render_css
  %t6 = call double @render_css()
  ret double 0.0
}

define double @render_header() {
entry:
  %t0 = getelementptr [32 x i8], [32 x i8]* @.str85, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [113 x i8], [113 x i8]* @.str86, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  %t2 = getelementptr [72 x i8], [72 x i8]* @.str87, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t2)
  ret double 0.0
}

define double @render_footer() {
entry:
  %t0 = getelementptr [47 x i8], [47 x i8]* @.str88, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [99 x i8], [99 x i8]* @.str89, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  %t2 = getelementptr [9 x i8], [9 x i8]* @.str90, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t2)
  %t3 = getelementptr [117 x i8], [117 x i8]* @.str91, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  %t4 = getelementptr [187 x i8], [187 x i8]* @.str92, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t4)
  %t5 = getelementptr [24 x i8], [24 x i8]* @.str93, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  ret double 0.0
}

define double @render_home() {
entry:
  ; call render_head
  ; string: "anemone"
  %t1 = fadd double 0.0, 0.0
  %t0 = call double @render_head(double %t1)
  ; call render_header
  %t2 = call double @render_header()
  %t3 = getelementptr [32 x i8], [32 x i8]* @.str94, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  %t4 = getelementptr [267 x i8], [267 x i8]* @.str95, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t4)
  %t5 = getelementptr [298 x i8], [298 x i8]* @.str96, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  %t6 = getelementptr [114 x i8], [114 x i8]* @.str97, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t6)
  %t7 = getelementptr [36 x i8], [36 x i8]* @.str98, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t7)
  %t8 = getelementptr [74 x i8], [74 x i8]* @.str99, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t8)
  %t9 = getelementptr [5 x i8], [5 x i8]* @.str100, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t9)
  ; call print_buffer
  %t10 = call double @print_buffer()
  %t11 = getelementptr [6 x i8], [6 x i8]* @.str101, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t11)
  %t12 = getelementptr [24 x i8], [24 x i8]* @.str102, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t12)
  %t13 = getelementptr [36 x i8], [36 x i8]* @.str103, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t13)
  %t14 = getelementptr [108 x i8], [108 x i8]* @.str104, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t14)
  %t15 = getelementptr [46 x i8], [46 x i8]* @.str105, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t15)
  %t16 = getelementptr [31 x i8], [31 x i8]* @.str106, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t16)
  %t17 = getelementptr [207 x i8], [207 x i8]* @.str107, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t17)
  ; call render_footer
  %t18 = call double @render_footer()
  ret double 0.0
}

define double @render_about() {
entry:
  ; call render_head
  ; string: "anemone | About"
  %t1 = fadd double 0.0, 0.0
  %t0 = call double @render_head(double %t1)
  ; call render_header
  %t2 = call double @render_header()
  %t3 = getelementptr [23 x i8], [23 x i8]* @.str108, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  %t4 = getelementptr [52 x i8], [52 x i8]* @.str109, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t4)
  %t5 = getelementptr [27 x i8], [27 x i8]* @.str110, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  %t6 = getelementptr [247 x i8], [247 x i8]* @.str111, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t6)
  %t7 = getelementptr [179 x i8], [179 x i8]* @.str112, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t7)
  %t8 = getelementptr [65 x i8], [65 x i8]* @.str113, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t8)
  %t9 = getelementptr [7 x i8], [7 x i8]* @.str114, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t9)
  %t10 = getelementptr [11 x i8], [11 x i8]* @.str115, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t10)
  ; call render_footer
  %t11 = call double @render_footer()
  ret double 0.0
}

define double @render_blog() {
entry:
  ; call render_head
  ; string: "anemone | Blog"
  %t1 = fadd double 0.0, 0.0
  %t0 = call double @render_head(double %t1)
  ; call render_header
  %t2 = call double @render_header()
  %t3 = getelementptr [24 x i8], [24 x i8]* @.str116, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  ; call print_buffer
  %t4 = call double @print_buffer()
  %t5 = getelementptr [6 x i8], [6 x i8]* @.str117, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  ; call render_footer
  %t6 = call double @render_footer()
  ret double 0.0
}

define double @render_post() {
entry:
  ; call render_head
  ; string: "anemone | Post"
  %t1 = fadd double 0.0, 0.0
  %t0 = call double @render_head(double %t1)
  ; call render_header
  %t2 = call double @render_header()
  %t3 = getelementptr [10 x i8], [10 x i8]* @.str118, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  ; call print_buffer
  %t4 = call double @print_buffer()
  %t5 = getelementptr [11 x i8], [11 x i8]* @.str119, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t5)
  ; call render_footer
  %t6 = call double @render_footer()
  ret double 0.0
}

define double @render_rss() {
entry:
  %t0 = getelementptr [68 x i8], [68 x i8]* @.str120, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [68 x i8], [68 x i8]* @.str121, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  ; call print_buffer
  %t2 = call double @print_buffer()
  %t3 = getelementptr [17 x i8], [17 x i8]* @.str122, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t3)
  ret double 0.0
}

define double @main() {
entry:
  ; call render_home
  %t0 = call double @render_home()
  ret double 0.0
}

