; NERD Compiled Program
; Generated by NERD Bootstrap Compiler

declare double @llvm.fabs.f64(double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.minnum.f64(double, double)
declare double @llvm.maxnum.f64(double, double)

declare i32 @printf(i8*, ...)

declare i8* @nerd_http_get(i8*)
declare i8* @nerd_http_post(i8*, i8*)
declare void @nerd_http_free(i8*)
declare i8* @nerd_http_get_json(i8*)
declare i8* @nerd_http_post_json(i8*, i8*)
declare i8* @nerd_http_post_json_body(i8*, i8*)
declare i8* @nerd_http_request(i8*, i8*, i8*, i8*)
declare i8* @nerd_http_get_full(i8*, i8*)
declare i8* @nerd_http_post_full(i8*, i8*, i8*)
declare i8* @nerd_http_put(i8*, i8*, i8*)
declare i8* @nerd_http_delete(i8*, i8*)
declare i8* @nerd_http_patch(i8*, i8*, i8*)
declare i8* @nerd_http_auth_bearer(i8*)
declare i8* @nerd_http_auth_basic(i8*, i8*)

declare i8* @nerd_mcp_list(i8*)
declare i8* @nerd_mcp_send(i8*, i8*, i8*)
declare i8* @nerd_mcp_use(i8*, i8*, i8*)
declare i8* @nerd_mcp_init(i8*)
declare i8* @nerd_mcp_resources(i8*)
declare i8* @nerd_mcp_read(i8*, i8*)
declare i8* @nerd_mcp_prompts(i8*)
declare i8* @nerd_mcp_prompt(i8*, i8*, i8*)
declare i8* @nerd_mcp_log(i8*, i8*)
declare void @nerd_mcp_free(i8*)

declare i8* @nerd_llm_claude(i8*)
declare void @nerd_llm_free(i8*)

declare i8* @nerd_json_new()
declare i8* @nerd_json_parse(i8*)
declare i8* @nerd_json_get_string(i8*, i8*)
declare double @nerd_json_get_number(i8*, i8*)
declare i32 @nerd_json_get_bool(i8*, i8*)
declare i8* @nerd_json_get_object(i8*, i8*)
declare i32 @nerd_json_count(i8*, i8*)
declare i32 @nerd_json_has(i8*, i8*)
declare void @nerd_json_set_string(i8*, i8*, i8*)
declare void @nerd_json_set_number(i8*, i8*, double)
declare void @nerd_json_set_bool(i8*, i8*, i32)
declare i8* @nerd_json_stringify(i8*)
declare void @nerd_json_free(i8*)
declare void @nerd_json_free_string(i8*)

@.fmt_num = private constant [4 x i8] c"%g\0A\00"
@.fmt_str = private constant [4 x i8] c"%s\0A\00"
@.fmt_int = private constant [6 x i8] c"%.0f\0A\00"

@.str0 = private constant [20 x i8] c"Welcome to NERD CMS\00"
@.str1 = private constant [36 x i8] c"Powered by No Effort Required, Done\00"

define double @main() {
entry:
  %t0 = getelementptr [20 x i8], [20 x i8]* @.str0, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t0)
  %t1 = getelementptr [36 x i8], [36 x i8]* @.str1, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t1)
  %t2 = fadd double 0.0, 5.0
  %t3 = fadd double 0.0, 3.0
  %t4 = fadd double %t2, %t3
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_num, i32 0, i32 0), double %t4)
  ret double 0.0
}

